server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: lifesaver-api
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# ML Service Configuration
ml:
  service:
    url: http://localhost:5001

# Logging Configuration
logging:
  level:
    com.lifesaver: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 